### ISSUE TITLE
Incompatibility of libraries

### ISSUE THREAD

**Issue by karol-wojcik** [contentful/contentful-management.php#129]
Hi,

There is a problem with using the library alongside with main library for content delivery: https://github.com/contentful/contentful.php
There is a version mismatch in "contentful/core".
When do you plan to release updated management lib?

**Comment by dborsatto** [comment]
Hey there,
Yes, I'm aware of this issue. Unfortunately for personal reasons I couldn't update yet this library to use the latest version of contentful/core, but it's my current top priority and hopefully should be done by end of week.

Cheers,

Davide

**Comment by karol-wojcik** [comment]
Hi Davide! Thank you for quick reply! Can't wait to see the updated lib in action :)

**Comment by dborsatto** [comment]
Hey @karol-wojcik ,

I just wanted to let you know that I've just released version 2.0 of this library, which should resolve the incompatibility you mention. Please let me know if you're still experiencing issues!

Cheers,

Davide
