### ISSUE TITLE
Error while executing generate:entry-classes command

### ISSUE THREAD

**Issue by fomalhaut79** [contentful/contentful-management.php#132]
Hi, I was not able to generate entry-classes due to this error: Fatal error: Uncaught TypeError: Argument 1 passed to PhpParser\PrettyPrinterAbstract::p() must implement interface PhpParser\Node, string given. Please let me know if you need more details to investigate this. Thanks.

**Comment by dborsatto** [comment]
Hey, which version of PHPParser are you using? The SDK currently only supports version 3.

**Comment by Rankarusu** [comment]
I'm getting the same error. It's been a while since this issue was closed. Is there support for v4 yet?
