### ISSUE TITLE
Missing NodesValidation Resource and Mapper classes

### ISSUE THREAD

**Issue by emsyzz** [contentful/contentful-management.php#134]
There is validation element `nodes: {}` for RichText even without any added validation which is not represented by any existing class and pulling content types from management API results in exception.

**Comment by emsyzz** [comment]
Found out that `EnabledNodeTypesValidation` is also missing.

**Comment by yadakhov** [comment]
Thank you for your PR.  https://github.com/contentful/contentful-management.php/pull/135 . We will review.

**Comment by CupOfTea696** [comment]
So is `EnabledMarksValidation`.

**Comment by e1himself** [comment]
Any progress here?

**Comment by pgrigoruta** [comment]
Thanks @emsyzz and sorry for the so long response time. We have just released version 2.2.1 with your PR, slightly changed for coding standards and test coverage.
