### ISSUE TITLE
How to handle rate limit

### ISSUE THREAD

**Issue by tranthienbinh1989** [contentful/contentful-management.php#140]
Hi there,

I saw that there are a config for retry with Javascript sdk `retryOnError: true`
Do we have this config with PHP sdk? if not do we have any to handle the retry logic when the the client reaches the rate limit?

**Comment by pgrigoruta** [comment]
We just added this feature in the latest release, check documentation at https://github.com/contentful/contentful-management.php#rate-limits-and-retrying

**Comment by ray-itech** [comment]
Hello,

Is there a version fo the contentful delivery API for retrying?

**Comment by Sebb767** [comment]
Hi Ray, the Contentful delivery API currently does not support automatically retrying. If you need that feature, I can put it on the roadmap :)

**Comment by ray-itech** [comment]
Yes, please add to the roadmap.
