### ISSUE TITLE
Calling getId() on new resources results in TypeError

### ISSUE THREAD

**Issue by jankramer** [contentful/contentful-management.php#141]
The following code results in an error:

```
$entry = new Contentful\Management\Resource\Entry('blogPost');
$entry->getId();

TypeError: Return value of Contentful\Management\Resource\Entry::getSystemProperties() must be an instance of Contentful\Management\SystemProperties\Entry, null returned
```
In previous versions (1.x) of this library, `getId()` on a new entry or any other type of resource would return `NULL`, as I'd expect. Was it intentional to disallow calls to `getId()` on new resources? At least it shouldn't throw a TypeError, I guess.

**Comment by pgrigoruta** [comment]
We introduced this in an effort to make better use of type hinting.

I think the easiest to work with new/existing entries without throwing the fatal error is to use the jsonSerialize() method:

`$client = new \Contentful\Management\Client('YOUR-KEY');
$environment = $client->getEnvironmentProxy('YOUR-SPACE', 'YOUR-ENV');
$entry = new \Contentful\Management\Resource\Entry('blogPost');

$entry->jsonSerialize(); //sys will be null

$environment->create($entry);

$entry->jsonSerialize(); //sys will be a Contentful\Management\SystemProperties\Entry instance
`
