### ISSUE TITLE
Provide additional detail during validation errors

### ISSUE THREAD

**Issue by atrauzzi** [contentful/contentful-management.php#142]
I'm wondering if it would be possible to populate the exception thrown by the SDK when there's a validation error with more detail?

Right now I just get the message "validation error", but am not guided as to which field the error was triggered for or what the nature of that error is.

**Comment by pgrigoruta** [comment]
@atrauzzi  this should be populated, looking at the SDK code , the body of the response is passed to the exception object. Can you provide a specific example so we can better understand what you're after?
