### ISSUE TITLE
Issue with getting Validation array field in response

### ISSUE THREAD

**Issue by ajaykumar00711** [contentful/contentful-management.php#143]
**### Looking for this type response with Validation field**

{
      "id": "developmentCategory",
      "name": "Development Category",
      "type": "Symbol",
      "localized": true,
      "required": false,
      "validations": [
        {
          "in": [
            "Cognitive Development",
            "Emotional Development",
            "Social Development",
            "Parent Self-care",
            "Misc."
          ]
        }
      ],

### **But getting Fields array without Validations details.**

#fields: array:18 [▼
    "headline" => array:1 [▶]
    "gradeLevel" => array:1 [▶]
    "emailSubjectLine" => array:1 [▶]
    "developmentCategory" => array:1 [▼
      "en-US" => "Social Development"
    ]
    "audioLink" => array:1 [▶]
    "contextAndIssue" => array:1 [▶]
    "goodNews" => array:1 [▶]
    "illustration" => array:1 [▶]
    "whatsGoingOnText" => array:1 [▶]
    "ideasIntro" => array:1 [▶]
    "idea" => array:1 [▶]
    "idea2" => array:1 [▶]
    "idea3" => array:1 [▶]
    "idea4" => array:1 [▶]
    "idea5" => array:1 [▶]
    "reflection" => array:1 [▶]
    "linksToRelevantTools" => array:1 [▶]
    "citation" => array:1 [▶]
  ]

I have used both APIS content delivery api and content management api with PHP SDK.

**Comment by ajaykumar00711** [comment]
$contentTypes = $environmentProxy->getContentTypes();
Shows this error CMA API - 


Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Class '\Contentful\Management\Mapper\ContentType\Validation\NodesValidation' not found

**Comment by pgrigoruta** [comment]
This has been fixed in the lasted 2.2.1 release.
