### ISSUE TITLE
Incorrect implementation of the source environment parameter

### ISSUE THREAD

**Issue by dborsatto** [contentful/contentful-management.php#147]
In #145 the method `Contentful\Management\Proxy\SpaceProxy::create()` received a 4th parameter, but the way it's implemented is incorrect, as it clearly breaks `CreatableInterface`.

Resources which may have an extra parameter in creation headers are supposed to have that parameter added to the resource object directly (think of the content type ID in entries, or org ID in spaces), and not here as a parameter to `create`, as this method is supposed to work with _all_ resources which implement `CreatableInterface`. What happens if I try to set the environment source parameter while creating any other resource? It will cause an error, as the `setSourceEnv` method does not exist.

I know It's not really my place any more, but I still work with this library as a user from time to time and I believe this is an incorrect implementation conceptually, regardless of the context. You really should not be using methods that have not been defined in an interface 🤷‍♂

**Comment by pgrigoruta** [comment]
Thanks for the advice, makes sense! We will implement the change shortly.

**Comment by pgrigoruta** [comment]
Fixed in https://github.com/contentful/contentful-management.php/commit/9bc638436986ff8bb763237e357d3bd3a415a9cd
