### ISSUE TITLE
Missing EnabledNodeTypesValidation, EnabledMarksValidation & 

### ISSUE THREAD

**Issue by ngeleedst** [contentful/contentful-management.php#150]
Hi,

Currently we are using this package with great succes! Powerful package and the super handy functionality to generate classes based on content models in Contentful. This last part throwing an error because of the missing validation classes that i am using in content models:

- EnabledNodeTypesValidation
- EnabledMarksValidation

Their is also a field type missing: RichText in the BaseCodeGenerator.

What i would like to do is add the RichtText type to BaseCodeGenerator and the Validation classes with stub for now and create a pull request?

Is this acceptable or are you already developing above issues?

**Comment by pgrigoruta** [comment]
Thanks @ngeleedst , we have this on our radar and we plan to correct all missing validation classes in the next month. By the way, your PR looks good and will reach the core, we just want to make sure we catch all other cases and cover them with tests.

**Comment by pgrigoruta** [comment]
This has been merged into the latest version, thanks again for the contribution!
