### ISSUE TITLE
Missing documentation for populating media field with multiple values

### ISSUE THREAD

**Issue by tobiassjosten** [contentful/contentful-management.php#157]
I've got a content type with a field containing multiple images. When I examine an entry of that type, it looks like so:

```
array(2) {
  [0] =>
  array(1) {
    'sys' =>
    array(3) {
      'type' =>
      string(4) "Link"
      'linkType' =>
      string(5) "Asset"
      'id' =>
      string(22) "7Iu3xRVvOOK9WTkpPD5JTC"
    }
  }
  [1] =>
  array(1) {
    'sys' =>
    array(3) {
      'type' =>
      string(4) "Link"
      'linkType' =>
      string(5) "Asset"
      'id' =>
      string(22) "2sX3nNprxD22HHzWcx5iB1"
    }
  }
}
```

My problem is that when I upload a file, create and publish an asset for it, and add the asset's Link to the entry's field array, using `setField()`, saving the entry gives me "422 Unprocessable Entity".

What am I doing wrong?

**Comment by pgrigoruta** [comment]
Thanks for noticing this! I have updated the documentation. The proper way to push existing assets is to use the Link object, see below:

`$images = [
    new \Contentful\Core\Api\Link('2PngieRxZeL854z0IDPZho2', 'Asset'),
    new \Contentful\Core\Api\Link('4O0kU2nI3PM2ot6tTWnVJJd', 'Asset'),
];


$entry = new \Contentful\Management\Resource\Entry('product');
$entry->setField('name','en-US','product name');
$entry->setField('productImages', 'en-US', $images);

$environmentProxy->create($entry);`

I am going to close this issue, feel free to re-open if you need more help.
