### ISSUE TITLE
PHP 8

### ISSUE THREAD

**Issue by mrbenosborne** [contentful/contentful-management.php#163]
Hi :wave: 

Will this package be updated to be used with PHP 8?

Thanks

**Comment by mrbenosborne** [comment]
Hi, 

Any update on this?

**Comment by mrbenosborne** [comment]
@Sebb767 great thanks for the reply.

**Comment by winkbrace** [comment]
We are waiting on this too. Good luck with the tests :)

**Comment by Sebb767** [comment]
Hi @winkbrace @mrbenosborne ; I've just released version 3.2.0, which officially supports PHP8! Thank you for your patience :)

**Comment by winkbrace** [comment]
That's great! Thanks so much for the effort :)
