### ISSUE TITLE
Range validation with floats causes TypeError

### ISSUE THREAD

**Issue by emsyzz** [contentful/contentful-management.php#165]
It's possible to set field's range validation values as floats through UI, even for fields that are meant to store floating point numbers. This causes `RangeValidator` construction to fail with `TypeError`.
![image](https://user-images.githubusercontent.com/3846682/118275514-2eb86b00-b4cf-11eb-9172-dda93c3349fe.png)
```
TypeError: Argument 1 passed to Contentful\Management\Resource\ContentType\Validation\RangeValidation::__construct() must be of the type int or null, float given
```

**Comment by Sebb767** [comment]
This is now released with [4.0.0](https://github.com/contentful/contentful-management.php/releases/tag/4.0.0). Thank you very much for contributing!
