### ISSUE TITLE
Symfony 6 support

### ISSUE THREAD

**Issue by mdubbelman** [contentful/contentful-management.php#167]
Could you please add support for Symfony 6? It has just been released and this package and ontentful/contentful-bundle are the only packages that are holding us back from updating to Symfony 6.

Thanks!

**Comment by Sebb767** [comment]
With [contentful-management version 4.0](https://github.com/contentful/contentful-management.php/releases/tag/4.0.0) and [ContentfulBundle version 7.0](https://github.com/contentful/contentful-management.php/releases/tag/4.0.0) you're now able to use Symfony 6. These versions contain some (minor) breaking changes, so be sure to check the release notes :)
