### ISSUE TITLE
Update to v4 core

### ISSUE THREAD

**Issue by mic2100** [contentful/contentful-management.php#173]
Hi,

Is there anyway this could be updated to use core v4? 

Currently v4 of this package requires v3 of the core. This is causing us problems because v3 relies on older versions of the libraries and we are unable to update other packages. I do believe v4 fixes these issues.

I need to be able to update jean85/pretty-package-versions to v2 but the core v3 code is set to ^1.5 and the v4 code is set the ^1.5|^2.0.

Thanks Mike

**Comment by boserup** [comment]
@mic2100 I reached out to someone at Contentful who told me, that the engineering team is in the process of updating and managing the PHP management SDK. So expect the v4 core update to happen soon.

**Comment by Sebb767** [comment]
We're taking up the issue, the update should be ready by the end of the week :)

**Comment by wlasnapl** [comment]
Is there some update?

**Comment by Sebb767** [comment]
This is now supported with [v.4.1.0](https://github.com/contentful/contentful-management.php/releases/tag/4.1.0) :)
