### ISSUE TITLE
symfony/console require mismatch with Magento 2.4.4-p6

### ISSUE THREAD

**Issue by Seppo-Konttinen-Solteq** [contentful/contentful-management.php#177]
Problem 1
- Root composer.json requires contentful/contentful-management ^4.1 -> satisfiable by contentful/contentful-management[4.1.0].
- contentful/contentful-management 4.1.0 requires symfony/console ^5.0|^6.0 -> found symfony/console[v5.0.0-BETA1, ..., v5.4.32, v6.0.0-BETA1, ..., v6.4.1] but these were not loaded, likely because it conflicts with another require.

magento/composer module requires "symfony/console": "~4.4.0". Also "contentful/contentful" acceptes ~4.0 ("symfony/console": "~2.7|~3.0|~4.0|^5.0|^6.0") so could this module also accept it?

**Comment by Seppo-Konttinen-Solteq** [comment]
Hi @Sebb767 .

Are you able to comment on this :)

Thanks.

**Comment by Sebb767** [comment]
Hi @Seppo-Konttinen-Solteq ,

Symfony 4.4 is end-of-life: https://symfony.com/releases/4.4 and will also be dropped by contentful/contentful.php in the next release. Is it possible for you to use [v4.0.0](https://github.com/contentful/contentful-management.php/releases/tag/4.0.0) of contentful/contentful-management.php which still supports older Symfony versions?

**Comment by Seppo-Konttinen-Solteq** [comment]
Hi @Sebb767 .

I'm afraid that contentful/contentful-management.php is incompatible with contentful/core 4.0.0 which is needed by contentful/contentful 7.0.1 which seems to be first that is really compatible with PHP8.x.

So it seems that I am in a bit problem here now between Contentful and Magento requires :)

Problem 1
    - Root composer.json requires contentful/contentful-management 4.0.0 -> satisfiable by contentful/contentful-management[4.0.0].
    - contentful/contentful-management 4.0.0 requires contentful/core ^3.0 -> found contentful/core[3.0.0, ..., 3.2.0] but the package is fixed to 4.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

**Comment by Sebb767** [comment]
It seems you're right. I'll push a minor fix to allow Symfony 4.4 again.

**Comment by Seppo-Konttinen-Solteq** [comment]
Hi @Sebb767.

Thank you. When I could expect the fix to be done?

**Comment by Seppo-Konttinen-Solteq** [comment]
Hi @Sebb767 .

Any info when the minor fix would be added?

Thanks.

**Comment by Sebb767** [comment]
I've released [v4.1.2](https://github.com/contentful/contentful-management.php/releases/tag/4.1.2), which should fix this issue

**Comment by Seppo-Konttinen-Solteq** [comment]
Works. Thanks.
