### ISSUE TITLE
PublishedContentType removal

### ISSUE THREAD

**Issue by dborsatto** [contentful/contentful-management.php#32]
As we're not going to enforce relations between `Entry` and `ContentType` any time soon (if ever), I'm wondering whether we should remove `PublishedContentType` (along with `PublishedSystemProperties`), as the reason for having a different implementation was to have some ways to connect `Entry` and `ContentType`.

Given the situation, I don't see that many reasons for keeping it around...

**Comment by realityking** [comment]
While it's true that we scratched the idea of enforcing the relation in the SDK, the API still does it.

If I wanna know what fields are writable in an entry, I need the published content type :/

**Comment by dborsatto** [comment]
Yes, but there is no real reason for having the `/public/content_types` endpoint return something different from a regular `ContentType`, this is the part that doesn't convince me. A `ContentType` and a `PublishedContentType` are essentially the same (extremely minor differences), yet we treat them as **completely** different objects, with nothing in common...

**Comment by dborsatto** [comment]
Refactored in #47
