### ISSUE TITLE
Uniform use of URI vs URL

### ISSUE THREAD

**Issue by dborsatto** [contentful/contentful-management.php#34]
Right now code is using both `URI` and `URL` without any specific convention.
I propose using `URI` as the standard (given it has the broadest meaning), except where the name comes from data stored in Contentful, where we should not change the name.

Notably, this would imply renaming `SpaceScopedResourceInterface::getResourceUrlPart` to `getResourceUriPart`.

**Comment by realityking** [comment]
Makes sense to me, go for it 👍
