### ISSUE TITLE
Increase body size in getResponseBodySummary

### ISSUE THREAD

**Issue by rande** [contentful/contentful-management.php#90]
Can you increase the byte limit in ``getResponseBodySummary`` ? Some usefull information get cut ;)

512 is better than 120.

```
Client error: `POST https://api.contentful.com/spaces/95wnqgvmhlea/assets` resulted in a `422 Unprocessable Entity` response:\n
{\n
  "sys": {\n
    "type": "Error",\n
    "id": "ValidationFailed"\n
  },\n
  "message": "Validation error",\n
  "details": {\n
     (truncated...)\n
```

**Comment by dborsatto** [comment]
Hey @rande,

I can take a look into that, but Guzzle exceptions should be wrapped into custom exceptions in the SDK where you can access things like message and details. Is that not working for you?

**Comment by rande** [comment]
sorry, the issue is not on your side, the limit is hardcoded in guzzle...
