### ISSUE TITLE
Empty thumbnail on uploaded asset

### ISSUE THREAD

**Issue by rande** [contentful/contentful-management.php#91]
## Error

The upload works fine and the asset is created properly on the contentful, however there is no image preview in the UI.

### References

https://app.contentful.com/spaces/95wnqgvmhlea/assets/4LW4eQoHBmSkOwMg2AE8wW

<img width="1137" alt="screen shot 2017-10-18 at 12 00 09" src="https://user-images.githubusercontent.com/14672/31712625-f64a8834-b3fb-11e7-9401-f8e956b2c6b5.png">

## Expected Result

The image is available.

## Code

```php
            $guesser = MimeTypeGuesser::getInstance();

            $upload = $contentful->upload->create(new Upload($file->getContents()));

            $asset = $contentful->asset->create((new Asset())
                ->setTitle('fr-FR', $file->getFilename())
                ->setFile('fr-FR', new LocalUploadFile(
                    $file->getFilename(),
                    $guesser->guess($file->getPathname()),
                    $upload->asLink()
                ))
            );
```

## Analysis

I just look into the networks call in chrome, look like the association is fine and respect the documentation (https://www.contentful.com/developers/docs/references/content-management-api/#/reference/uploads)

<img width="423" alt="screen shot 2017-10-18 at 12 05 38" src="https://user-images.githubusercontent.com/14672/31712936-e153351a-b3fc-11e7-9ff6-1a6d16eba35b.png">

If I click on the image in the edit form, an message appear : "Cannot publish until processing has finished"

## Versions

```
cocur/slugify                     dev-master 4244332    MIT
contentful/contentful             dev-master 8c2c306    MIT
contentful/contentful-management  dev-master 4942efd    MIT
doctrine/annotations              dev-master ff479e6    MIT
doctrine/cache                    dev-master beb0fa3    MIT
doctrine/collections              dev-master 42c4039    MIT
doctrine/common                   dev-master a3e240f    MIT
doctrine/dbal                     dev-master 9d70667    MIT
doctrine/inflector                dev-master 40daa06    MIT
doctrine/lexer                    dev-master cc709ba    MIT
guzzlehttp/guzzle                 6.3.0                 MIT
guzzlehttp/promises               dev-master e9cdab6    MIT
guzzlehttp/psr7                   dev-master d2537c8    MIT
league/flysystem                  dev-master 6a35577    MIT
pixel418/markdownify              dev-master 0160677    LGPL
psr/http-message                  dev-master f6561bf    MIT
psr/log                           dev-master 4ebe3a8    MIT
symfony/console                   3.4.x-dev 0b3c686     MIT
symfony/debug                     dev-master a76f02e    MIT
symfony/dotenv                    3.4.x-dev 94d0115     MIT
symfony/filesystem                3.4.x-dev 113da03     MIT
symfony/finder                    3.4.x-dev 6db4a8d     MIT
symfony/http-foundation           dev-master 17209e3    MIT
symfony/polyfill-mbstring         dev-master 2ec8b39    MIT
symfony/var-dumper                3.4.x-dev 41c9a13     MIT
symfony/yaml                      3.4.x-dev e99024f     MIT
```

**Comment by dborsatto** [comment]
Hey @rande,

after uploading an asset, you have to _process_ it (https://www.contentful.com/developers/docs/references/content-management-api/#/reference/assets/asset-processing).

In the SDK, you can do that like this:

``` php
// After having created the asset
$asset->process();
```

You can optionally pass a locale parameter, otherwise the process will be invoked for all available locales 🙂

**Comment by rande** [comment]
ok ;)
